"""Create documents table

Revision ID: 6d50bacb5a33
Revises: 1520708e62a8
Create Date: 2026-02-15 12:00:26.453641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '6d50bacb5a33'
down_revision = '1520708e62a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), server_default=text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('STATUTES', 'MINUTES', 'FINANCIAL_REPORTS', 'OTHER', name='document_category', native_enum=False), nullable=False),
    sa.Column('access_level', sa.Enum('PUBLIC', 'MEMBERS', 'ADMINISTRATORS', name='access_level', native_enum=False), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_access', 'documents', ['access_level'], unique=False)
    op.create_index('idx_documents_category', 'documents', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_category', table_name='documents')
    op.drop_index('idx_documents_access', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
